// Generated by CoffeeScript 2.2.4
(function() {
  var TestMLBridge;

  require('testml/bridge');

  module.exports = TestMLBridge = class TestMLBridge extends TestML.Bridge {
    add(a, b) {
      return Number(a) + Number(b);
    }

    sub(a, b) {
      return a - b;
    }

  };

}).call(this);
