// Generated by CoffeeScript 2.3.0
(function() {
  var TestMLBridge;

  require('testml/bridge');

  module.exports = TestMLBridge = class TestMLBridge extends TestML.Bridge {
    hash_lookup(hash, key) {
      return hash[key];
    }

    get_env(name) {
      return process.env[name];
    }

  };

  // vim: ft=coffee sw=2:

}).call(this);
