// Generated by CoffeeScript 2.3.0
(function() {
  var TestMLBridge;

  require('testml/bridge');

  module.exports = TestMLBridge = class TestMLBridge extends TestML.Bridge {
    hash_lookup(hash, key) {
      return hash[key];
    }

    get_env(name) {
      return process.env[name];
    }

    add(x, y) {
      return x + y;
    }

    sub(x, y) {
      return x - y;
    }

    mine() {
      var Mine;
      return new (Mine = class Mine {});
    }

    str_nums(str) {
      return _.map(_.split(str, ' '), function(x) {
        return Number(x);
      });
    }

  };

}).call(this);
