// Generated by CoffeeScript 2.3.1
(function() {
  require('../pegex');

  Pegex.Grammar = class Grammar {
    constructor(_ = {}) {
      ({file: this.file, text: this.text, tree: this.tree} = _);
      this.make_tree;
      this;
    }

    make_tree() {
      var compiler;
      if (this.tree != null) {
        return this.tree;
      }
      if (this.text == null) {
        if (this.file != null) {
          require('fs');
          this.text = fs.readFileSync(this.file).toString();
        } else {
          throw "Can't create a grammar. No tree or text or file.";
        }
      }
      require('../pegex/compiler');
      compiler = new Pegex.Compiler;
      return this.tree = compiler.compile(this.text).tree;
    }

  };

  // TODO later
// compile_into_module: (module)->

}).call(this);
