// Generated by CoffeeScript 2.3.1
(function() {
  require('../pegex');

  Pegex.Input = class Input {
    constructor(a = {}) {
      ({string: this.string} = a);
      ({file: this.file} = a);
      ({handle: this.handle} = a);
      this._buffer = '';
      this._is_eof = false;
      this._is_open = false;
      this._is_close = false;
    }

    read() {
      var buffer;
      if (!this._is_open) {
        throw "Attempted Pegex.Input.read before open";
      }
      if (this._is_eof) {
        throw "Attempted Pegex.Input.read after EOF";
      }
      buffer = this._buffer;
      this._buffer = null;
      this._is_eof = true;
      return buffer;
    }

    open() {
      if (this._is_open || this._is_close) {
        throw "Attempted to reopen Pegex.Input object";
      }
      if (this.string != null) {
        this._buffer = this.string;
      } else {
        throw "Pegex.Input.open failed. No source to open.";
      }
      this._is_open = true;
      return this;
    }

    close() {
      if (this._is_close) {
        throw "Attempted to close an unopen Pegex.Input object";
      }
      this._is_open = false;
      this._is_close = true;
      this._buffer = null;
      return this;
    }

  };

}).call(this);
