// Generated by CoffeeScript 2.3.1
(function() {
  require('../pegex/grammar');

  require('../pegex/parser');

  Pegex.Module = class Module {
    parse(input) {
      var parser;
      parser = new this.parser(this.grammar(this.receiver));
      return parser.parse(input);
    }

    grammar() {
      var class_name;
      class_name = `${this.name}.Grammar`;
      return eval(`class ${class_name} extends Pegex.Grammar`);
    }

    parser() {
      return "TODO";
    }

    receiver() {
      return "TODO";
    }

  };

}).call(this);
