// Generated by CoffeeScript 2.3.1
(function() {
  require('../pegex');

  Pegex.Receiver = class Receiver {
    constructor(a = {}) {
      ({wrap: this.wrap} = a);
      if (this.wrap == null) {
        this.wrap = false;
      }
    }

    flatten(array, times) {
      var elem, i, len, result;
      if (times == null) {
        times = -1;
      }
      if (!times--) {
        return array;
      }
      result = [];
      for (i = 0, len = array.length; i < len; i++) {
        elem = array[i];
        if (elem instanceof Array) {
          result = result.concat(this.flatten(elem, times));
        } else {
          result.push(elem);
        }
      }
      return result;
    }

  };

}).call(this);
