// Generated by CoffeeScript 2.3.1
(function() {
  require('../pegex/receiver');

  Pegex.Tree = class Tree extends Pegex.Receiver {
    gotrule(got) {
      if (got === void 0) {
        return;
      }
      if (this.parser.parent['-wrap']) {
        return {
          [`${this.parser.rule}`]: got
        };
      }
      return got;
    }

    final(got) {
      if (got !== void 0) {
        return got;
      }
      return [];
    }

  };

}).call(this);
