// Generated by CoffeeScript 2.3.1
(function() {
  global.TestML = (function() {
    class TestML {};

    TestML.VERSION = '0.0.28';

    TestML.browser = false;

    TestML.env = (global.process || {}).env || {};

    return TestML;

  }).call(this);

}).call(this);
