// Generated by CoffeeScript 2.3.0
(function() {
  global.TestML = (function() {
    class TestML {};

    TestML.VERSION = '0.0.10';

    TestML.browser = false;

    return TestML;

  }).call(this);

}).call(this);
