// Generated by CoffeeScript 2.3.0
(function() {
  module.exports = TestML.StdLib = class StdLib {
    true() {
      return true;
    }

    false() {
      return false;
    }

  };

  // vim: ft=coffee sw=2:

}).call(this);
