RUNTIME_LANG := perl
ROOT := ../..

#------------------------------------------------------------------------------
default:

test: test-tap

#------------------------------------------------------------------------------
include $(ROOT)/.makefile/runtime.mk
include pkg/package.mk
