RUNTIME_LANG := elixir
ROOT := ../..
TEST_TAP_DEPS := $(ROOT)/src/node_modules

#------------------------------------------------------------------------------
default:

test: test-tap

#------------------------------------------------------------------------------
include $(ROOT)/.makefile/runtime.mk
