// Generated by CoffeeScript 2.3.0
(function() {
  require('../../testml/run');

  require('../../testml/tap');

  module.exports = TestML.Run.TAP = class TAP extends TestML.Run {
    static run(file) {
      (new this).from_file(file).test();
    }

    constructor(params = {}) {
      super(params);
      this.tap = new TestML.TAP;
      return;
    }

    test_begin() {}

    test_end() {
      this.tap.done_testing();
    }

    test_eq(got, want, label) {
      if (_.isString(want) && got !== want && want.match(/\n/) && (this.getv('Diff') || this.getp('DIFF'))) {
        if (!TestML.browser) {
          global.JsDiff = require('diff');
        }
        this.tap.fail(label);
        this.tap.diag(JsDiff.createTwoFilesPatch('want', 'got', want, got, '', '', {
          context: 3
        }));
      } else {
        this.tap.is_eq(got, want, label);
      }
    }

  };

  // vim: ft=coffee sw=2:

}).call(this);
