// Generated by CoffeeScript 2.3.0
(function() {
  require('../../testml/run');

  require('../../testml/tap');

  module.exports = TestML.Run.TAP = class TAP extends TestML.Run {
    static run(file) {
      (new this).from_file(file).test();
    }

    constructor(params = {}) {
      super(params);
      ({output: this.output} = params);
      this.tap = new TestML.TAP;
      return;
    }

    testml_begin() {}

    testml_end() {
      this.tap.done_testing();
      if (TestML.browser && this.output) {
        this.output.value = this.tap.output;
      }
    }

    testml_eq(got, want, label) {
      var diff;
      diff = _.isString(want) && want.match(/\n/) && (this.getv('Diff') || this.getp('DIFF'));
      return this.tap.is_eq(got, want, label, diff);
    }

    testml_like(got, want, label) {
      return this.tap.like(got, want, label);
    }

    testml_has(got, want, label) {
      return this.tap.has(got, want, label);
    }

    testml_list_has(got, want, label) {
      return this.tap.list_has(got, want, label);
    }

    warn(msg) {
      return this.tap.diag(msg);
    }

  };

  // vim: ft=coffee sw=2:

}).call(this);
