LANG := coffee
ROOT := ../..
TEST_TAP_DEPS := ../node_modules

#------------------------------------------------------------------------------
default:

test: test-tap

#------------------------------------------------------------------------------
include $(ROOT)/.makefile/runtime.mk
