RUNTIME_LANG := perl5
ROOT := ../..

export MAKE

#------------------------------------------------------------------------------
default:

test: test-tap

#------------------------------------------------------------------------------
include $(ROOT)/.makefile/runtime.mk
include pkg/package.mk
